{
 "title": "Pekko Dispatcher Metrics",
 "description": "The Dispatchers instrumentation captures metrics on the underlying executor service for Pekko dispatchers.",
 "tags": [
  "akka",
  "dispatcher"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Application",
    "query": {
     "query": "label_values({__name__=~\"jvm.*\"}, job)"
    }
   },
   {
    "name": "Instance",
    "query": {
     "query": "label_values(executor_threads_min{job=~\"$Application\"},instance)"
    }
   },
   {
    "name": "Dispatcher",
    "query": {
     "query": "label_values(executor_threads_min{job=~\"$Application\",instance=~\"$Instance\"},name)"
    }
   },
   { "name": "Interval", "query": "1m,10m,30m,1h,6h,12h,1d" },
   {
    "name": "Type",
    "query": {
     "query": "label_values(executor_threads_min{job=~\"$Application\",instance=~\"$Instance\"},type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Executor Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number Of Active Threads",
   "type": "timeseries",
   "description": "Tracks the number of threads in use.",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(executor_threads_total_sum{job=~\"$Application\",instance=~\"$Instance\",name=~\"$Dispatcher\",type=~\"$Type\"}[$Interval])\n/\nrate(executor_threads_total_count{job=~\"$Application\",instance=~\"$Instance\",name=~\"$Dispatcher\",type=~\"$Type\"}[$Interval])",
     "legendFormat": "threads total - {{ name }} ({{ instance }})"
    },
    {
     "expr": "rate(executor_threads_active_sum{job=~\"$Application\",instance=~\"$Instance\",name=~\"$Dispatcher\",type=~\"$Type\"}[$Interval])\n/\nrate(executor_threads_active_count{job=~\"$Application\",instance=~\"$Instance\",name=~\"$Dispatcher\",type=~\"$Type\"}[$Interval])",
     "legendFormat": "threads active - {{ name }} ({{ instance }})"
    }
   ]
  },
  {
   "title": "Number Of Tasks",
   "type": "graph",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(executor_tasks_completed_total{job=~\"$Application\",instance=~\"$Instance\",name=~\"$Dispatcher\",type=~\"$Type\"}[$Interval])",
     "legendFormat": "tasks completed - {{ name }} ({{ instance }})"
    }
   ]
  },
  {
   "title": "Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(executor_queue_size_sum{job=~\"$Application\",instance=~\"$Instance\",name=~\"$Dispatcher\",type=~\"$Type\"}[$Interval])\n/\nrate(executor_queue_size_count{job=~\"$Application\",instance=~\"$Instance\",name=~\"$Dispatcher\",type=~\"$Type\"}[$Interval])",
     "legendFormat": "{{ name }} ({{ type }})"
    }
   ]
  },
  {
   "title": "Min/Max Number of Threads",
   "type": "timeseries",
   "description": "Tracks minimum/maximum number of Threads of the executors.",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "executor_threads_min{job=~\"$Application\",instance=~\"$Instance\",name=~\"$Dispatcher\",type=~\"$Type\"}",
     "legendFormat": "min - {{ name }} ({{ instance }})"
    },
    {
     "expr": "executor_threads_max{job=~\"$Application\",instance=~\"$Instance\",name=~\"$Dispatcher\",type=~\"$Type\"}",
     "legendFormat": "max - {{ name }} ({{ instance }})"
    }
   ]
  },
  {
   "title": "Executor parallelism",
   "type": "graph",
   "description": "Tracks executor parallelism.",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "executor_parallelism{job=~\"$Application\",instance=~\"$Instance\",name=~\"$Dispatcher\",type=~\"$Type\"}",
     "legendFormat": "{{ name }} ({{ instance }})"
    }
   ]
  },
  {
   "title": "Time in queue",
   "type": "timeseries",
   "description": "Tracks the time that tasks spend on the executor service's queue",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(executor_time_in_queue_seconds_sum{job=~\"$Application\",instance=~\"$Instance\",name=~\"$Dispatcher\",type=~\"$Type\"}[$Interval])\n/\nrate(executor_time_in_queue_seconds_count{job=~\"$Application\",instance=~\"$Instance\",name=~\"$Dispatcher\",type=~\"$Type\"}[$Interval])",
     "legendFormat": "{{ name }} ({{ instance }})"
    }
   ]
  }
 ]
}