{
 "title": "Cluster traffic",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "open streaming sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "streaming_sessions_count", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "# of streaming messages per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(streaming_messages_total[1m])) by (direction, type)",
     "legendFormat": "{{type}} {{direction}}"
    }
   ]
  },
  {
   "title": "# of HTTP calls per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\nirate(roundtrip_http_seconds_count[5m]) > 0\n) \nby (ditto_request_method)",
     "legendFormat": "{{ditto_request_method}}"
    }
   ]
  },
  { "title": "Connectivity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "open connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(connection_client) by (type)",
     "legendFormat": "[{{type}}] Overall"
    }
   ]
  },
  {
   "title": "active connections over the last 5 minutes",
   "type": "graph",
   "description": "Connections which delivered metrics in the last 7 days",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (ditto_connection_type) (count by (instance, ditto_connection_type, ditto_connection_id) (increase (connectivity_message_mapping_seconds_count[5m]) > 0))",
     "legendFormat": "[{{ditto_connection_type}}] Overall"
    }
   ]
  },
  {
   "title": "# of messages per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(connectivity_message_mapping_seconds_count{segment=\"overall\"}[5m]) > 0) by (direction, ditto_connection_type) > 0",
     "legendFormat": "[{{ditto_connection_type}}] {{direction}}"
    }
   ]
  },
  {
   "title": "messages mapping times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg((idelta(connectivity_message_mapping_seconds_sum{segment=\"overall\"}[1m]) / idelta(connectivity_message_mapping_seconds_count{segment=\"overall\"}[1m])) > 0) by (direction)",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  { "title": "Concierge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "# of enforcements per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(concierge_enforcements_seconds_count{segment=\"overall\",channel!=\"live\"}[5m]) > 0) by (category, resource, outcome)",
     "legendFormat": "{{outcome}}| {{category}} {{resource}}"
    },
    {
     "expr": "sum(irate(concierge_enforcements_seconds_count{segment=\"overall\",channel=\"live\"}[5m]) > 0) by (category, resource, outcome)",
     "legendFormat": "live: {{outcome}}| {{category}} {{resource}}"
    }
   ]
  },
  {
   "title": "enforcement times",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg((idelta(concierge_enforcements_seconds_sum{segment=\"overall\",channel!=\"live\"}[5m]) / idelta(concierge_enforcements_seconds_count{segment=\"overall\",channel!=\"live\"}[5m])) > 0) by (category, resource, outcome)",
     "legendFormat": "{{outcome}}| {{category}} {{resource}}"
    },
    {
     "expr": "avg((idelta(concierge_enforcements_seconds_sum{segment=\"overall\",channel=\"live\"}[5m]) / idelta(concierge_enforcements_seconds_count{segment=\"overall\",channel=\"live\"}[5m])) > 0) by (category, resource, outcome)",
     "legendFormat": "live: {{outcome}}| {{category}} {{resource}}"
    }
   ]
  },
  { "title": "MongoDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "# of journal inserts/reads per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(akka_persistence_mongo_journal_scala_official_write_append_seconds_count[1m]))",
     "legendFormat": "inserts"
    },
    {
     "expr": "sum(rate(akka_persistence_mongo_journal_scala_official_read_max_seq_seconds_count[1m]))",
     "legendFormat": "reads"
    }
   ]
  }
 ]
}