{
 "title": "Concierge Enforcement Queues",
 "tags": [ "beeper" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Host",
    "query": "label_values(graph_actor_enqueue_success_total, instance)"
   },
   {
    "name": "Actor",
    "query": "label_values(graph_actor_enqueue_success_total{job=\"concierge\"}, class)"
   }
  ]
 },
 "panels": [
  {
   "title": "Queue size",
   "type": "graph",
   "description": "The current queue size in the actor (dequeued - enqueued)",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(-graph_actor_dequeue_total{class=~\"$Actor\", job=\"concierge\", instance=~\"$Host\"}\n+\ngraph_actor_enqueue_success_total{class=~\"$Actor\", job=\"concierge\", instance=~\"$Host\"}) or vector(0)",
     "legendFormat": "{{class}} ({{instance}})"
    }
   ]
  },
  {
   "title": "enqueued / second",
   "type": "graph",
   "description": "How many messages are enqueued after processing by the actor.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(graph_actor_enqueue_success_total{class=~\"$Actor\", job=\"concierge\", instance=~\"$Host\"}[1m])",
     "legendFormat": "{{class}} ({{instance}})"
    }
   ]
  },
  {
   "title": "enqueue failures / second",
   "type": "graph",
   "description": "How many messages failed to be enqueued.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(graph_actor_enqueue_failure_total{class=~\"$Actor\", job=\"concierge\", instance=~\"$Host\"}[1m]) or vector(0)",
     "legendFormat": "{{class}} failure ({{instance}})"
    },
    {
     "expr": "irate(graph_actor_enqueue_dropped_total{class=~\"$Actor\", job=\"concierge\", instance=~\"$Host\"}[1m]) or vector(0)",
     "legendFormat": "{{class}} dropped ({{instance}})"
    }
   ]
  },
  {
   "title": "Outstanding enforcement tasks",
   "type": "graph",
   "description": "Shows how many enforcement tasks are currently waiting to be executed.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scheduled_enforcement_tasks_total - completed_enforcement_tasks_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "dequeued / second",
   "type": "graph",
   "description": "How many messages are dequeued for processing by the actor.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(graph_actor_dequeue_total{class=~\"$Actor\", job=\"concierge\", instance=~\"$Host\"}[1m])",
     "legendFormat": "{{class}} ({{instance}})"
    }
   ]
  }
 ]
}