{
 "title": "Connectivity Acks",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Host",
    "query": {
     "query": "label_values(connectivity_ack_handling_seconds_count, instance)"
    }
   },
   {
    "name": "Connection",
    "query": {
     "query": "label_values(connectivity_ack_handling_seconds_count,ditto_connection_id)"
    }
   },
   {
    "name": "ConnectionType",
    "query": {
     "query": "label_values(connectivity_ack_handling_seconds_count,ditto_connection_type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Total ACK count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# total issued ACKs in selected date picker interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(connectivity_ack_handling_seconds_count{instance=~\"$Host\", ditto_connection_id=~\"$Connection\", ditto_connection_type=~\"$ConnectionType\", ditto_ack_success=\"true\"}[$__range])) by (ditto_connection_type) > 0",
     "legendFormat": "[{{ditto_connection_type}}] ACK success"
    },
    {
     "expr": "sum(increase(connectivity_ack_handling_seconds_count{instance=~\"$Host\", ditto_connection_id=~\"$Connection\", ditto_connection_type=~\"$ConnectionType\", ditto_ack_success=\"false\"}[$__range])) by (ditto_connection_type, ditto_ack_redeliver) > 0",
     "legendFormat": "[{{ditto_connection_type}}] NACK, redeliver: {{ditto_ack_redeliver}}"
    }
   ]
  },
  { "title": "ACK rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "# issued ACKs per minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(connectivity_ack_handling_seconds_count{segment=\"overall\", instance=~\"$Host\", ditto_connection_id=~\"$Connection\", ditto_connection_type=~\"$ConnectionType\", ditto_ack_success=\"true\"}[1m])) by (ditto_ack_success, ditto_connection_type) > 0",
     "legendFormat": "[{{ditto_connection_type}}] ACK successful: {{ditto_ack_success}}"
    }
   ]
  },
  {
   "title": "# issued ACKs per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(connectivity_ack_handling_seconds_count{segment=\"overall\", instance=~\"$Host\", ditto_connection_id=~\"$Connection\", ditto_connection_type=~\"$ConnectionType\", ditto_ack_success=\"true\"}[5m])) by (ditto_ack_success, ditto_connection_type) > 0",
     "legendFormat": "[{{ditto_connection_type}}] ACK successful: {{ditto_ack_success}}"
    }
   ]
  },
  {
   "title": "ACK times",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9,sum(irate(connectivity_ack_handling_seconds_bucket{segment=\"overall\", instance=~\"$Host\", ditto_connection_id=~\"$Connection\", ditto_connection_type=~\"$ConnectionType\", ditto_ack_success=\"true\"}[5m])) by (ditto_connection_type,ditto_ack_success,le))",
     "legendFormat": "[{{ditto_connection_type}}] ACK successful: {{ditto_ack_success}}"
    }
   ]
  },
  { "title": "NACK rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "# issued NACKs per minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(connectivity_ack_handling_seconds_count{segment=\"overall\", instance=~\"$Host\", ditto_connection_id=~\"$Connection\", ditto_connection_type=~\"$ConnectionType\", ditto_ack_success=\"false\"}[1m])) by (ditto_ack_success, ditto_ack_redeliver, ditto_connection_type) > 0",
     "legendFormat": "[{{ditto_connection_type}}] Redeliver NACK: {{ditto_ack_redeliver}}"
    }
   ]
  },
  {
   "title": "# issued NACKs per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(connectivity_ack_handling_seconds_count{segment=\"overall\", instance=~\"$Host\", ditto_connection_id=~\"$Connection\", ditto_connection_type=~\"$ConnectionType\", ditto_ack_success=\"false\"}[5m])) by (ditto_ack_success, ditto_ack_redeliver, ditto_connection_type) > 0",
     "legendFormat": "[{{ditto_connection_type}}] Redeliver NACK: {{ditto_ack_redeliver}}"
    }
   ]
  },
  {
   "title": "NACK times",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9,sum(irate(connectivity_ack_handling_seconds_bucket{segment=\"overall\", instance=~\"$Host\", ditto_connection_id=~\"$Connection\", ditto_connection_type=~\"$ConnectionType\", ditto_ack_success=\"false\"}[5m])) by (ditto_connection_type,ditto_ack_success,le))",
     "legendFormat": "[{{ditto_connection_type}}] Redeliver NACK: {{ditto_ack_redeliver}}"
    }
   ]
  },
  {
   "title": "# messages awaiting acks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(connectivity_ack_handling_counter) by (ditto_connection_type)"
    }
   ]
  }
 ]
}