{
 "title": "Connectivity live status",
 "tags": [ "email" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Overview count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "FAILURE",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "title": "MISCONFIGURE",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 5 }
   ]
  },
  {
   "title": "OPEN",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 6 }
   ]
  },
  {
   "title": "Failures per connection type",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "connection-type.keyword",
       "id": "5",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "3", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "3", "type": "count" }
     ],
     "query": "ditto-log-tag.keyword:connection-live-status-failed",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Misconfigured per connection type",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "connection-type.keyword",
       "id": "5",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "3", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "3", "type": "count" }
     ],
     "query": "ditto-log-tag.keyword:connection-live-status-misconfigured",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Live status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "FAILUREs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Failures",
     "bucketAggs": [
      { "field": "@timestamp", "id": "1", "settings": { "interval": "auto", "offset": "0", "trimEdges": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "3", "type": "count" }
     ],
     "query": "ditto-log-tag.keyword:connection-live-status-failed",
     "timeField": "@timestamp"
    },
    {
     "alias": "Failures",
     "bucketAggs": [
      {
       "field": "connection-id.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "1",
       "settings": { "interval": "auto", "min_doc_count": "0", "offset": "0", "trimEdges": "1" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "3", "type": "count" }
     ],
     "query": "ditto-log-tag.keyword:connection-live-status-failed",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MISCONFIGUREDs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Misconfigured",
     "bucketAggs": [
      { "field": "@timestamp", "id": "1", "settings": { "interval": "auto", "offset": "0", "trimEdges": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "3", "type": "count" }
     ],
     "query": "ditto-log-tag.keyword:connection-live-status-misconfigured",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "OPENs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Open",
     "bucketAggs": [
      { "field": "@timestamp", "id": "1", "settings": { "interval": "auto", "offset": "0", "trimEdges": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "3", "type": "count" }
     ],
     "query": "ditto-log-tag.keyword:connection-live-status-open",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}