{
 "title": "External Metrics",
 "tags": [ "beeper" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Application",
    "query": {
     "query": "label_values(akka_persistence_mongo_journal_scala_official_read_max_seq_seconds_bucket, job)"
    }
   },
   {
    "name": "Instance",
    "query": {
     "query": "label_values(up{job=~\"$Application\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "MongoDB writes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MongoDB Journal Times - insert",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(akka_persistence_mongo_journal_scala_official_write_append_seconds_bucket{job=~\"$Application\", instance=~\"$Instance\"}[5m]) > 0) by (le, job, instance))",
     "legendFormat": "{{job}} ({{instance}}) - mean",
     "target": "aliasByNode(stats.gauges.$Application.$Host.akka-persistence-mongo.journal.casbah.write.append.timer.p50, 2, 3, -1)"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(akka_persistence_mongo_journal_scala_official_write_append_seconds_bucket{job=~\"$Application\", instance=~\"$Instance\"}[5m]) > 0) by (le, job, instance))",
     "legendFormat": "{{job}} ({{instance}}) - 95th percentile",
     "target": "aliasByNode(stats.gauges.$Application.$Host.akka-persistence-mongo.journal.casbah.write.append.timer.p95, 2, 3, -1)"
    }
   ]
  },
  {
   "title": "MongoDB Journal interaction per second - insert",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(akka_persistence_mongo_journal_scala_official_write_append_seconds_count{job=~\"$Application\", instance=~\"$Instance\"}[1m]))",
     "legendFormat": "inserts/seconds (1m)",
     "target": "alias(sumSeries(stats.gauges.$Application.$Host.akka-persistence-mongo.journal.casbah.write.append.timer.m1_rate), 'inserts/second 1min')"
    },
    {
     "expr": "sum(rate(akka_persistence_mongo_journal_scala_official_write_append_seconds_count{job=~\"$Application\", instance=~\"$Instance\"}[5m]))",
     "legendFormat": "inserts/seconds (5m)",
     "target": "alias(sumSeries(stats.gauges.$Application.$Host.akka-persistence-mongo.journal.casbah.write.append.timer.m5_rate), 'inserts/second 5min')"
    },
    {
     "expr": "sum(rate(akka_persistence_mongo_journal_scala_official_write_append_seconds_count{job=~\"$Application\", instance=~\"$Instance\"}[15m]))",
     "legendFormat": "inserts/seconds (15m)",
     "target": "alias(sumSeries(stats.gauges.$Application.$Host.akka-persistence-mongo.journal.casbah.write.append.timer.m15_rate), 'inserts/second 15min')"
    }
   ]
  },
  { "title": "MongoDB reads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "MongoDB Journal Times - read",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(akka_persistence_mongo_journal_scala_official_read_max_seq_seconds_bucket{job=~\"$Application\", instance=~\"$Instance\"}[5m]) > 0) by (le, job, instance))",
     "legendFormat": "{{job}} ({{instance}}) - mean",
     "target": "aliasByNode(stats.gauges.$Application.$Host.akka-persistence-mongo.journal.casbah.read.replay.timer.p50, 2, 3, -1)"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(akka_persistence_mongo_journal_scala_official_read_max_seq_seconds_bucket{job=~\"$Application\", instance=~\"$Instance\"}[5m]) > 0) by (le, job, instance))",
     "legendFormat": "{{job}} ({{instance}}) - 95th percentile",
     "target": "aliasByNode(stats.gauges.$Application.$Host.akka-persistence-mongo.journal.casbah.read.replay.timer.p95, 2, 3, -1)"
    }
   ]
  },
  {
   "title": "MongoDB Journal interaction per second - read",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(akka_persistence_mongo_journal_scala_official_read_max_seq_seconds_count{job=~\"$Application\", instance=~\"$Instance\"}[1m]))",
     "legendFormat": "reads/second (1m)",
     "target": "alias(sumSeries(stats.gauges.$Application.$Host.akka-persistence-mongo.journal.casbah.read.replay.timer.m1_rate), 'reads/second 1min')"
    },
    {
     "expr": "sum(rate(akka_persistence_mongo_journal_scala_official_read_max_seq_seconds_count{job=~\"$Application\", instance=~\"$Instance\"}[5m]))",
     "legendFormat": "reads/second (5m)",
     "target": "alias(sumSeries(stats.gauges.$Application.$Host.akka-persistence-mongo.journal.casbah.read.replay.timer.m5_rate), 'reads/second 5min')"
    },
    {
     "expr": "sum(rate(akka_persistence_mongo_journal_scala_official_read_max_seq_seconds_count{job=~\"$Application\", instance=~\"$Instance\"}[15m]))",
     "legendFormat": "reads/second (15m)",
     "target": "alias(sumSeries(stats.gauges.$Application.$Host.akka-persistence-mongo.journal.casbah.read.replay.timer.m15_rate), 'reads/second 15min')"
    }
   ]
  },
  { "title": "Things Search Updater", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "MongoDB times - insert/update",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(\nsum(idelta({__name__=~\"things_search_thing_.*_seconds_sum\"}[1m])) by (update_type)\n/\nsum(idelta({__name__=~\"things_search_thing_.*_seconds_count\"}[1m])) by (update_type)\n)",
     "legendFormat": "{{update_type}}",
     "target": "aliasByNode(stats.timers.ThingsSearch.$Host.trace.things_thing_*.elapsed-time.median, 5,3,7)"
    }
   ]
  },
  {
   "title": "MongoDB interactions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta({__name__=~\"things_search_thing_.*_seconds_count\"}[1m])) by (instance, update_type)",
     "legendFormat": "{{update_type}} ({{instance}})",
     "target": "alias(sumSeries(stats.timers.ThingsSearch.$Host.trace.thing_*.elapsed-time.count), 'count')"
    }
   ]
  }
 ]
}