{
 "title": "Gateway Traces",
 "tags": [ "beeper" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": {
     "query": "label_values(up{job=\"gateway\"},instance)"
    }
   },
   { "name": "Api", "query": "1,2" }
  ]
 },
 "panels": [
  { "title": "Roundtrip 90th percentile", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Things Http Roundtrip (API 2)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(irate(roundtrip_http_seconds_bucket{ditto_request_path=~\"/api/2/things/.*\", ditto_request_path!=\"/api/2/things/messages\", instance=~\"$Instance\"}[5m]) > 0) by (le)) or vector(0)"
    }
   ]
  },
  {
   "title": "Things /messages Http Roundtrip (API 2)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(irate(roundtrip_http_seconds_bucket{ditto_request_path=~\"/api/2/things/messages\", instance=~\"$Instance\"}[5m]) > 0) by (le)) or vector(0)"
    }
   ]
  },
  {
   "title": "Things-Search Http Roundtrip (API 2)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(irate(roundtrip_http_seconds_bucket{ditto_request_path=~\"/api/2/search/things/.*\", ditto_statusCode=~\"2[0-9]{2}\", instance=~\"$Instance\"}[5m]) > 0) by (le)) or vector(0)",
     "target": "(sum(rate(roundtrip_http_api_1_search_things_x_sum{ditto_statusCode=~\"2[0-9]{2}\"}[1m]) >= 0)  / sum(rate(roundtrip_http_api_1_search_things_x_count{ditto_statusCode=~\"2[0-9]{2}\"}[1m]) >= 0))"
    }
   ]
  },
  {
   "title": "Global roundtrip average (API 2 + other)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(irate(roundtrip_http_seconds_bucket{instance=~\"$Instance\"}[5m]) > 0) by (le)) or vector(0)",
     "target": "(sum(rate(roundtrip_http_api_1_search_things_x_sum{ditto_statusCode=~\"2[0-9]{2}\"}[1m]) >= 0)  / sum(rate(roundtrip_http_api_1_search_things_x_count{ditto_statusCode=~\"2[0-9]{2}\"}[1m]) >= 0))"
    }
   ]
  },
  {
   "title": "Roundtrip 90th percentile - Api $Api",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }
  },
  {
   "title": "Things Http Roundtrip",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 6 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(irate(roundtrip_http_seconds_bucket{ditto_request_path=~\"/api/[[Api]]/things/.*\", ditto_request_path!=\"/api/[[Api]]/things/messages\", ditto_statusCode=~\"2[0-9]{2}\", instance=~\"$Instance\"}[5m]) > 0) by (le)) or vector(0)"
    }
   ]
  },
  {
   "title": "Things /messages Http Roundtrip",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 6 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(irate(roundtrip_http_seconds_bucket{ditto_request_path=\"/api/[[Api]]/things/messages\", instance=~\"$Instance\"}[5m]) > 0) by (le)) or vector(0)"
    }
   ]
  },
  {
   "title": "Things-Search Http Roundtrip",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 6 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(irate(roundtrip_http_seconds_bucket{ditto_request_path=~\"/api/[[Api]]/search/things/.*\", ditto_statusCode=~\"2[0-9]{2}\", instance=~\"$Instance\"}[5m]) > 0) by (le)) or vector(0)",
     "target": "(sum(rate(roundtrip_http_api_1_search_things_x_sum{ditto_statusCode=~\"2[0-9]{2}\"}[1m]) >= 0)  / sum(rate(roundtrip_http_api_1_search_things_x_count{ditto_statusCode=~\"2[0-9]{2}\"}[1m]) >= 0))"
    }
   ]
  },
  { "title": "Status Codes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Http Status Code 2xx count per second",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(roundtrip_http_seconds_count{ditto_statusCode=~\"2[0-9]{2}\", instance=~\"$Instance\"}[5m]) or vector(0))"
    }
   ]
  },
  {
   "title": "Http Status Code 4xx count per second",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(roundtrip_http_seconds_count{ditto_statusCode=~\"4[0-9]{2}\", instance=~\"$Instance\"}[5m]) or vector(0))"
    }
   ]
  },
  {
   "title": "Http Status Code 5xx count per second",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(roundtrip_http_seconds_count{ditto_statusCode=~\"5[0-9]{2}\", instance=~\"$Instance\"}[5m]) or vector(0))"
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "HTTP Command Processing Time (2xx) - 90th percentile",
   "type": "graph",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(irate(roundtrip_http_seconds_bucket{ditto_statusCode=~\"2[0-9]{2}\", instance=~\"$Instance\"}[5m]) > 0) by (ditto_request_method, ditto_request_path, ditto_statusCode, le)) or vector(0)",
     "legendFormat": "{{ditto_request_method}} - {{ditto_statusCode}} - {{ditto_request_path}}"
    }
   ]
  },
  {
   "title": "# of Processed HTTP commands (2xx) per second",
   "type": "graph",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\nirate(roundtrip_http_seconds_count{ditto_statusCode=~\"2[0-9]{2}\", instance=~\"$Instance\"}[5m]) > 0\n) \nby (ditto_request_method, ditto_request_path, ditto_statusCode)",
     "legendFormat": "{{ditto_request_method}} - {{ditto_statusCode}} - {{ditto_request_path}}"
    }
   ]
  },
  {
   "title": "Relative time per Trace",
   "type": "graph",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(idelta(roundtrip_http_seconds_sum{ditto_statusCode=~\"2[0-9]{2}\", instance=~\"$Instance\"}[1m])) by (ditto_request_method, ditto_request_path, ditto_statusCode)) > 0",
     "legendFormat": "{{ditto_request_method}} - {{ditto_statusCode}} - {{ditto_request_path}}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "HTTP Command Processing Time (5xx) - 90th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(irate(roundtrip_http_seconds_bucket{ditto_statusCode=~\"5[0-9]{2}\", instance=~\"$Instance\"}[5m]) > 0) by (ditto_request_method, ditto_request_path, ditto_statusCode, le))"
    }
   ]
  },
  {
   "title": "# of processed HTTP commands (5xx) per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(roundtrip_http_seconds_count{ditto_statusCode=~\"5[0-9]{2}\", instance=~\"$Instance\", ditto_channel!=\"live\"}[5m]) or vector(0))\n\nby (ditto_request_method, ditto_request_path, ditto_statusCode)",
     "legendFormat": "{{ditto_request_method}} - {{ditto_statusCode}} - {{ditto_request_path}}"
    }
   ]
  },
  { "title": "Other Traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "# of other traces per second",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(filter_auth_seconds_count{instance=~\"$Instance\"}[5m])) by (ditto_auth_type, ditto_auth_success)",
     "legendFormat": "Authentication: {{ditto_auth_type}} - Success: {{ditto_auth_success}}"
    },
    {
     "expr": "sum(irate(filter_auth_seconds_count{ditto_auth_error=\"true\"}[5m])) by (ditto_auth_type)",
     "legendFormat": "Authentication errors: {{ditto_auth_type}}"
    }
   ]
  },
  {
   "title": "Other Traces Processing Time - 90th percentile",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(irate(filter_auth_seconds_bucket{instance=~\"$Instance\"}[5m]) > 0) by (ditto_auth_type, ditto_auth_success, le)) or vector(0)",
     "legendFormat": "Authentication: {{ditto_auth_type}} - Success: {{ditto_auth_success}}"
    }
   ]
  },
  {
   "title": "# of complimentary requests per second",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(transactions_complimentary_clients_total[5m]))",
     "legendFormat": "complimentary requests"
    }
   ]
  }
 ]
}