{
 "title": "Hot Entities",
 "description": "Dashboard which shows Hot Entities",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Hot Things",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ceil(avg(hotThings))", "legendFormat": "Hot Things" }
   ]
  },
  {
   "title": "Hot Policies",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ceil(avg(hotPolicies))", "legendFormat": "Hot Policies" }
   ]
  },
  {
   "title": "Hot Search Updaters",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ceil(avg(hotSearchUpdaters))", "legendFormat": "Hot Search Updaters" }
   ]
  }
 ]
}