{
 "title": "JVM Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Application",
    "query": "label_values({__name__=~\"jvm.*\"}, job)"
   },
   {
    "name": "Instance",
    "query": "label_values(jvm_gc_seconds_count{job=\"$Application\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "JVM :: Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Garbage Collection Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "idelta(jvm_gc_seconds_sum{job=\"$Application\",instance=~\"$Instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "idelta(jvm_gc_seconds_count{job=\"$Application\",instance=~\"$Instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "JVM :: Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{region=\"heap\",job=\"$Application\", instance=~\"$Instance\"}",
     "legendFormat": "max: {{instance}}"
    },
    {
     "expr": "jvm_memory_committed_bytes{region=\"heap\",job=\"$Application\", instance=~\"$Instance\"}",
     "legendFormat": "committed: {{instance}}"
    },
    {
     "expr": "sum(idelta(jvm_memory_used_bytes_sum{region=\"heap\",job=\"$Application\", instance=~\"$Instance\"}[5m])) by (instance)\n/\nsum(idelta(jvm_memory_used_bytes_count{region=\"heap\",job=\"$Application\", instance=~\"$Instance\"}[5m])) by (instance)",
     "legendFormat": "used: {{instance}}"
    }
   ]
  },
  {
   "title": "Non-Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{region=\"non-heap\",job=\"$Application\", instance=~\"$Instance\"}",
     "legendFormat": "max: {{instance}}"
    },
    {
     "expr": "jvm_memory_committed_bytes{region=\"non-heap\",job=\"$Application\", instance=~\"$Instance\"}",
     "legendFormat": "committed: {{instance}}"
    },
    {
     "expr": "sum(idelta(jvm_memory_used_bytes_sum{region=\"non-heap\",job=\"$Application\", instance=~\"$Instance\"}[5m])) by (instance)\n/\nsum(idelta(jvm_memory_used_bytes_count{region=\"non-heap\",job=\"$Application\", instance=~\"$Instance\"}[5m])) by (instance)",
     "legendFormat": "used: {{instance}}"
    }
   ]
  },
  {
   "title": "Memory Pools",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_committed_bytes{job=~\"$Application\", instance=~\"$Instance\"}) by(instance, pool)",
     "legendFormat": "committed ({{pool}}): {{instance}}"
    },
    {
     "expr": "sum(idelta(jvm_memory_pool_used_bytes_sum{job=~\"$Application\", instance=~\"$Instance\"}[5m])) by(instance, pool)\n/\nsum(idelta(jvm_memory_pool_used_bytes_count{job=~\"$Application\", instance=~\"$Instance\"}[5m])) by (instance, pool)",
     "legendFormat": "used ({{pool}}): {{instance}}"
    }
   ]
  },
  { "title": "JVM :: Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_threads_peak{job=\"$Application\",instance=~\"$Instance\"})",
     "legendFormat": "peak"
    },
    {
     "expr": "sum(jvm_threads_total{job=\"$Application\",instance=~\"$Instance\"})",
     "legendFormat": "total"
    },
    {
     "expr": "sum(jvm_threads_daemon{job=\"$Application\",instance=~\"$Instance\"})",
     "legendFormat": "daemon"
    }
   ]
  }
 ]
}