{
 "title": "Kafka Consumer Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Connection Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kafka_consumer_connection_count)",
     "legendFormat": "number of connections total"
    }
   ]
  },
  {
   "title": "Connection Creation Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(irate(kafka_consumer_connection_creation_total[1m])) by (consumerId)",
     "legendFormat": "Connection Creation Rate - {{consumerId}}"
    }
   ]
  },
  {
   "title": "fetch times",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_fetch_latency_avg) by(consumerId)",
     "legendFormat": "Fetch latency avg - {{consumerId}}"
    },
    {
     "expr": "sum(irate(kafka_consumer_fetch_throttle_time_avg[1m])) by(consumerId)",
     "legendFormat": "Fetch throttle time avg - {{consumerId}}"
    }
   ]
  },
  {
   "title": "Rebalancing per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(irate(kafka_consumer_failed_rebalance_total[1m]))",
     "legendFormat": "Failed rebalances"
    },
    {
     "expr": "sum(irate(kafka_consumer_rebalance_total[1m]))",
     "legendFormat": "Rebalances"
    }
   ]
  },
  {
   "title": "fetch rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(kafka_consumer_fetch_total[1m]))",
     "legendFormat": "fetches/second total"
    },
    {
     "expr": "sum(irate(kafka_consumer_request_total[1m]))",
     "legendFormat": "requests/second total"
    }
   ]
  },
  {
   "title": "seconds since last heartbeat",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_last_heartbeat_seconds_ago) by(consumerId)",
     "legendFormat": "{{consumerId}}"
    }
   ]
  }
 ]
}