{
 "title": "Kubernetes Metrics",
 "tags": [ "email" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "host", "label": "Host:", "query": "label_values(host, host)" },
   {
    "name": "instance",
    "query": "label_values(host{host=~\"$host\"},instance)"
   },
   { "name": "namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{namespace=~\"$namespace\"}) by (phase)",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Pods running",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{phase=\"Running\",namespace=~\"$namespace\" } > 0) by (pod, phase)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods pending, failed, unknown",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{phase=~\"Failed|Unkown|Pending\",namespace=~\"$namespace\"} > 0) by (pod, phase)",
     "legendFormat": "{{phase}}: {{pod}}"
    }
   ]
  },
  {
   "title": "Service Restarts sum",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum by (pod)(delta(kube_pod_container_status_restarts_total{instance=~\"$host\",namespace=~\"$namespace\", namespace=~\"things-.*\"}[15m]) > 0))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Service restarts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(kube_pod_container_status_restarts_total{namespace=~\"$namespace\", namespace=~\"things-.*|deviceprovisioning-.\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Top 5 Memory Intense Pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(5,sum(container_memory_usage_bytes{image!=\"\",instance=~\"$host\",namespace=~\"$namespace\"}) by (pod, namespace))",
     "legendFormat": "{{pod}} ({{namespace}})"
    }
   ]
  },
  { "title": "Deployments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Deployments available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=~\"$namespace\"}) by (namespace, deployment)",
     "legendFormat": "{{deployment}} ({{namespace}})"
    }
   ]
  },
  {
   "title": "Deployments unavailable",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\"}) by (namespace, deployment)",
     "legendFormat": "{{deployment}} ({{namespace}})"
    }
   ]
  },
  { "title": "DaemonSet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "DaemonSets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (kube_daemonset_status_number_available{namespace=~\"$namespace\"})",
     "legendFormat": "available"
    },
    {
     "expr": "sum (kube_daemonset_status_number_ready{namespace=~\"$namespace\"})",
     "legendFormat": " ready"
    },
    {
     "expr": "sum (kube_daemonset_status_number_misscheduled{namespace=~\"$namespace\"})",
     "legendFormat": "misscheduled"
    },
    {
     "expr": "sum (kube_daemonset_status_number_unavailable{namespace=~\"$namespace\"})",
     "legendFormat": " unavailable"
    }
   ]
  },
  {
   "title": "DaemonSets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_daemonset_status_number_available{namespace=~\"$namespace\"}) by (namespace, daemonset)",
     "legendFormat": "{{daemonset}} ({{namespace}})"
    }
   ]
  },
  {
   "title": "DaemonSets unavailables",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (kube_daemonset_status_number_misscheduled{namespace=~\"$namespace\"} > 0) by (namespace, daemonset)",
     "legendFormat": "{{namespace}} ({{namespace}}) - misscheduled"
    },
    {
     "expr": "sum (kube_daemonset_status_number_unavailable{namespace=~\"$namespace\"} > 0) by (namespace, daemonset)",
     "legendFormat": "{{daemonset}} ({{namespace}}) - unavailable"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "CPU Idle Avg",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$host\"}[2m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Disk IO time / s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total{instance=~\"$host\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Load 1m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$host\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$host\"} + node_memory_Buffers_bytes{instance=~\"$host\"} + node_memory_Cached_bytes{instance=~\"$host\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Min Mem",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 10, "y": 42 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(node_memory_MemAvailable_bytes{instance=~\"$host\"}/node_memory_MemTotal_bytes{instance=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Least CPU Idle",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 12, "y": 42 },
   "format": "percentunit",
   "valueName": "min",
   "targets": [
    {
     "expr": "sort_desc(min(avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$host\"}[2m])) by (instance)))"
    }
   ]
  },
  {
   "title": "Min Space",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 14, "y": 42 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(node_filesystem_avail_bytes{mountpoint!~\".*(serviceaccount|proc|sys).*\",instance=~\"$host\"}/node_filesystem_size_bytes{mountpoint!~\".*(serviceaccount|proc|sys).*\",instance=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Node Storage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "min(node_filesystem_avail_bytes{mountpoint!~\".*(serviceaccount|proc|sys).*\", device!=\"overlay\", instance=~\"$host\"}/node_filesystem_size_bytes{mountpoint!~\".*(serviceaccount|proc|sys).*\", device!=\"overlay\", instance=~\"$host\"}) by (device, instance)",
     "legendFormat": "[{{device}}] {{instance}}"
    }
   ]
  }
 ]
}