{
 "title": "Persistence Entities",
 "description": "Dashboard which shows Entities managed by Akka Persistence",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Hot Things",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ceil(avg(hotThings))", "legendFormat": "Hot Things" }
   ]
  },
  {
   "title": "Thing Event Clean-Up",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(akka_persistence_mongo_journal_scala_official_write_append_seconds_count{job=\"things\"}[5m]))",
     "legendFormat": "persisted events"
    },
    {
     "expr": "sum(irate(cleanup_delete_events_total{job=\"things\"}[5m]))",
     "legendFormat": "deleted events"
    }
   ]
  },
  {
   "title": "Hot Policies",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ceil(avg(hotPolicies))", "legendFormat": "Hot Policies" }
   ]
  },
  {
   "title": "Policy Event Clean-Up",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(akka_persistence_mongo_journal_scala_official_write_append_seconds_count{job=\"policies\"}[5m]))",
     "legendFormat": "persisted events"
    },
    {
     "expr": "sum(irate(cleanup_delete_events_total{job=\"policies\"}[5m]))",
     "legendFormat": "deleted events"
    }
   ]
  },
  {
   "title": "Hot Search Updaters",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ceil(avg(hotSearchUpdaters))", "legendFormat": "Hot Search Updaters" }
   ]
  },
  {
   "title": "Connection Event Clean-Up",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(akka_persistence_mongo_journal_scala_official_write_append_seconds_count{job=\"connectivity\"}[5m]))",
     "legendFormat": "persisted events"
    },
    {
     "expr": "sum(irate(cleanup_delete_events_total{job=\"connectivity\"}[5m]))",
     "legendFormat": "deleted events"
    }
   ]
  }
 ]
}