{
 "title": "Pub-sub",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "messages published per sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pubsub_published_messages_total[1m])",
     "legendFormat": "pub {{instance}}"
    }
   ]
  },
  {
   "title": "topics ddata size in bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "pubsub_topics_size_bytes{name=\"thing-event-aware-sub-supervisor/subUpdater\"}",
     "legendFormat": "twin {{instance}}"
    },
    {
     "expr": "pubsub_topics_size_bytes{name=\"live-signal-aware-sub-supervisor/subUpdater\"}",
     "legendFormat": "live {{instance}}"
    },
    { "expr": "sum(pubsub_topics_size_bytes)", "legendFormat": "total" }
   ]
  },
  {
   "title": "messages received by subscribers per sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pubsub_true_positive_total[1m])",
     "legendFormat": "sub {{instance}}"
    }
   ]
  },
  {
   "title": "topics ddata size in bytes exact",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "metrics": [
      { "id": "4", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "tags:\"ddata\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "wasted bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100*irate(pubsub_false_positive_total[1m])/(irate(pubsub_false_positive_total[1m])+irate(pubsub_true_positive_total[1m]))",
     "legendFormat": "wasted {{instance}}"
    }
   ]
  },
  {
   "title": "acks ddata size in bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "pubsub_ack_size_bytes", "legendFormat": "{{instance}}" },
    { "expr": "sum(pubsub_ack_size_bytes)", "legendFormat": "total" }
   ]
  },
  {
   "title": "Published to dead letter queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "\"dead letters encountered\" AND \"Message [org.eclipse.ditto.internal.utils.pubsub.api.PublishSignal]\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "queued topics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pubsub_await_acknowledge", "legendFormat": "to-ack {{instance}}" },
    { "expr": "pubsub_await_update", "legendFormat": "to-flush {{instance}}" }
   ]
  }
 ]
}