# Copyright (c) 2020 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0

FROM docker.io/adoptopenjdk/openjdk11-openj9:jdk-11.0.12_7_openj9-0.27.0-alpine-slim

ARG TARGET_DIR
ARG SERVICE_STARTER
ARG SERVICE_VERSION

ENV HTTP_PORT=8080 \
    HOSTING_ENVIRONMENT=Docker \
    DITTO_HOME=/opt/ditto \
    DITTO_LOGS=/var/log/ditto

# Http port
EXPOSE 8080

RUN set -x \
    && apk upgrade --update-cache \
    && apk add --no-cache tini openssl \
    && apk add --no-cache --virtual .tmp-deps wget ca-certificates shadow \
    && groupadd --system --gid 1000 ditto \
    && useradd --no-log-init --system --home-dir $DITTO_HOME --shell /bin/sh --gid ditto --uid 1000 ditto \
    && mkdir -p $DITTO_HOME \
    && mkdir -p $DITTO_LOGS \
    && cd $DITTO_HOME \
    && ln -s ${SERVICE_STARTER}-${SERVICE_VERSION}-allinone.jar starter.jar \
    && chown -R ditto:ditto $DITTO_HOME \
    && cd $DITTO_LOGS \
    && chown -R ditto:ditto $DITTO_LOGS \
    && apk del .tmp-deps

USER ditto
WORKDIR $DITTO_HOME
ENTRYPOINT ["/sbin/tini", "--"]
CMD ["java", "-jar", "/opt/ditto/starter.jar"]

COPY ${TARGET_DIR}/${SERVICE_STARTER}-${SERVICE_VERSION}-allinone.jar $DITTO_HOME
