# Copyright (c) 2021 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0

FROM docker.io/arm64v8/eclipse-temurin:17-jdk

ARG TARGET_DIR
ARG SERVICE_STARTER
ARG SERVICE_VERSION
ARG JVM_CMD_ARGS=""
ARG MAIN_CLASS

ENV HTTP_PORT=8080 \
    HOSTING_ENVIRONMENT=Docker \
    DITTO_HOME=/opt/ditto \
    DITTO_LOGS=/var/log/ditto \
    JVM_CMD_ARGS_ENV=${JVM_CMD_ARGS} \
    MAIN_CLASS_ENV=${MAIN_CLASS} \
    CLASSPATH=/opt/ditto/*:/opt/ditto/extensions/*

# Http port
EXPOSE 8080

RUN set -x \
    && apt-get update \
    && apt-get install -y tini \
    && mkdir -p $DITTO_HOME \
    && mkdir -p $DITTO_LOGS \
    && groupadd --system --gid 1000 ditto \
    && useradd --no-log-init --system --home-dir $DITTO_HOME --shell /bin/sh --gid ditto --uid 1000 ditto \
    && cd $DITTO_HOME \
    && chown -R ditto:ditto $DITTO_HOME \
    && cd $DITTO_LOGS \
    && chown -R ditto:ditto $DITTO_LOGS

USER ditto
WORKDIR $DITTO_HOME
ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["sh", "-c", "exec java ${JVM_CMD_ARGS_ENV} ${MAIN_CLASS_ENV}"]

COPY ${TARGET_DIR}/${SERVICE_STARTER}-${SERVICE_VERSION}-allinone.jar $DITTO_HOME
