# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
{{- if or .Values.dittoui.enabled .Values.swaggerui.enabled }}
---
# "ui-config.json" read by the Ditto UI and the Swagger UI (served next to their index.html)
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ui-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "ditto.name" . }}-ui-config
{{ include "ditto.labels" . | indent 4 }}
data:
  ui-config.json: |-
{{ dict "environmentsURL" (dict "allowedOrigins" (.Values.dittoui.environmentsURL.allowedOrigins | default list)) | toPrettyJson | indent 4 }}
{{- end }}
