{
 "title": "[ditto] Gateway Traces",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Things Http Roundtrip",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "format": "ns",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum(rate(roundtrip_http_api_1_things_x_sum{ditto_statusCode=~\"2[0-9]{2}\"}[1m]) >= 0)  / sum(rate(roundtrip_http_api_1_things_x_count{ditto_statusCode=~\"2[0-9]{2}\"}[1m] )>= 0)))"
    }
   ]
  },
  {
   "title": "Things-Search Http Roundtrip",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "format": "ns",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(roundtrip_http_api_1_search_things_x_sum{ditto_statusCode=~\"2[0-9]{2}\"}[1m]) >= 0)  / sum(rate(roundtrip_http_api_1_search_things_x_count{ditto_statusCode=~\"2[0-9]{2}\"}[1m]) >= 0))"
    }
   ]
  },
  {
   "title": "Relations Http Roundtrip",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "format": "ns",
   "valueName": "current",
   "targets": [
    {}
   ]
  },
  {
   "title": "Http Status Code 200 count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(roundtrip_http_api_1_things_x_count{ditto_statusCode=~\"2[0-9]{2}\"}) or sum(up * 0))\r\n+ (sum(roundtrip_http_api_1_search_things_x_count{ditto_statusCode=~\"2[0-9]{2}\"}) or sum(up * 0))\r\n+ (sum(roundtrip_http_other_count{ditto_statusCode=~\"2[0-9]{2}\"}) or sum(up * 0))\r\n+ (sum(roundtrip_http_status_count{ditto_statusCode=~\"2[0-9]{2}\"}) or sum(up * 0))\r\n+ (sum(roundtrip_http_status_health_count{ditto_statusCode=~\"2[0-9]{2}\"}) or sum(up * 0))\r\n+ (sum(roundtrip_http_api_2_things_x_count{ditto_statusCode=~\"2[0-9]{2}\"}) or sum(up * 0))\r\n+ (sum(roundtrip_http_api_2_search_things_x_count{ditto_statusCode=~\"2[0-9]{2}\"}) or sum(up * 0))\r\n\r\n- (sum(roundtrip_http_api_1_things_x_count{ditto_statusCode=~\"2[0-9]{2}\" } offset 1m) or sum(up * 0))\r\n- (sum(roundtrip_http_api_1_search_things_x_count{ditto_statusCode=~\"2[0-9]{2}\"} offset 1m) or sum(up * 0))\r\n- (sum(roundtrip_http_other_count{ditto_statusCode=~\"2[0-9]{2}\"} offset 1m) or sum(up * 0))\r\n- (sum(roundtrip_http_status_count{ditto_statusCode=~\"2[0-9]{2}\"} offset 1m) or sum(up * 0))\r\n- (sum(roundtrip_http_status_health_count{ditto_statusCode=~\"2[0-9]{2}\"} offset 1m) or sum(up * 0))\r\n- (sum(roundtrip_http_api_2_things_x_count{ditto_statusCode=~\"2[0-9]{2}\"} offset 1m) or sum(up * 0))\r\n- (sum(roundtrip_http_api_2_search_things_x_count{ditto_statusCode=~\"2[0-9]{2}\"} offset 1m) or sum(up * 0))\r\n\r\n"
    }
   ]
  },
  {
   "title": "Http Status Code 500 count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(roundtrip_http_api_1_things_x_count{ditto_statusCode=~\"5[0-9]{2}\"}) or sum(up * 0))\r\n+ (sum(roundtrip_http_api_1_search_things_x_count{ditto_statusCode=~\"5[0-9]{2}\"}) or sum(up * 0))\r\n+ (sum(roundtrip_http_other_count{ditto_statusCode=~\"5[0-9]{2}\"}) or sum(up * 0))\r\n+ (sum(roundtrip_http_status_count{ditto_statusCode=~\"5[0-9]{2}\"}) or sum(up * 0))\r\n+ (sum(roundtrip_http_status_health_count{ditto_statusCode=~\"5[0-9]{2}\"}) or sum(up * 0))\r\n+ (sum(roundtrip_http_api_2_things_x_count{ditto_statusCode=~\"5[0-9]{2}\"}) or sum(up * 0))\r\n+ (sum(roundtrip_http_api_2_search_things_x_count{ditto_statusCode=~\"5[0-9]{2}\"}) or sum(up * 0))\r\n\r\n- (sum(roundtrip_http_api_1_things_x_count{ditto_statusCode=~\"5[0-9]{2}\" } offset 1m) or sum(up * 0))\r\n- (sum(roundtrip_http_api_1_search_things_x_count{ditto_statusCode=~\"5[0-9]{2}\"} offset 1m) or sum(up * 0))\r\n- (sum(roundtrip_http_other_count{ditto_statusCode=~\"5[0-9]{2}\"} offset 1m) or sum(up * 0))\r\n- (sum(roundtrip_http_status_count{ditto_statusCode=~\"5[0-9]{2}\"} offset 1m) or sum(up * 0))\r\n- (sum(roundtrip_http_status_health_count{ditto_statusCode=~\"5[0-9]{2}\"} offset 1m) or sum(up * 0))\r\n- (sum(roundtrip_http_api_2_things_x_count{ditto_statusCode=~\"5[0-9]{2}\"} offset 1m) or sum(up * 0))\r\n- (sum(roundtrip_http_api_2_search_things_x_count{ditto_statusCode=~\"5[0-9]{2}\"} offset 1m) or sum(up * 0))\r\n\r\n"
    }
   ]
  },
  {
   "title": "Http Status Code 400 count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(roundtrip_http_api_1_things_x_count{ditto_statusCode=~\"4[0-9]{2}\"}) or sum(up * 0))\r\n+ (sum(roundtrip_http_api_1_search_things_x_count{ditto_statusCode=~\"4[0-9]{2}\"}) or sum(up * 0))\r\n+ (sum(roundtrip_http_other_count{ditto_statusCode=~\"4[0-9]{2}\"}) or sum(up * 0))\r\n+ (sum(roundtrip_http_status_count{ditto_statusCode=~\"4[0-9]{2}\"}) or sum(up * 0))\r\n+ (sum(roundtrip_http_status_health_count{ditto_statusCode=~\"4[0-9]{2}\"}) or sum(up * 0))\r\n+ (sum(roundtrip_http_api_2_things_x_count{ditto_statusCode=~\"4[0-9]{2}\"}) or sum(up * 0))\r\n+ (sum(roundtrip_http_api_2_search_things_x_count{ditto_statusCode=~\"4[0-9]{2}\"}) or sum(up * 0))\r\n\r\n- (sum(roundtrip_http_api_1_things_x_count{ditto_statusCode=~\"4[0-9]{2}\" } offset 1m) or sum(up * 0))\r\n- (sum(roundtrip_http_api_1_search_things_x_count{ditto_statusCode=~\"4[0-9]{2}\"} offset 1m) or sum(up * 0))\r\n- (sum(roundtrip_http_other_count{ditto_statusCode=~\"4[0-9]{2}\"} offset 1m) or sum(up * 0))\r\n- (sum(roundtrip_http_status_count{ditto_statusCode=~\"4[0-9]{2}\"} offset 1m) or sum(up * 0))\r\n- (sum(roundtrip_http_status_health_count{ditto_statusCode=~\"4[0-9]{2}\"} offset 1m) or sum(up * 0))\r\n- (sum(roundtrip_http_api_2_things_x_count{ditto_statusCode=~\"4[0-9]{2}\"} offset 1m) or sum(up * 0))\r\n- (sum(roundtrip_http_api_2_search_things_x_count{ditto_statusCode=~\"4[0-9]{2}\"} offset 1m) or sum(up * 0))"
    }
   ]
  },
  {
   "title": "Http Command Processing Time (20x)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(roundtrip_http_api_1_things_x_sum{ditto_statusCode=~\"2[0-9]{2}\"}[1m]) >= 0) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method)  / sum(rate(roundtrip_http_api_1_things_x_count{ditto_statusCode=~\"2[0-9]{2}\"}[1m]) > 0) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method))"
    },
    {
     "expr": "(sum(rate(roundtrip_http_api_1_search_things_x_sum{ditto_statusCode=~\"2[0-9]{2}\"}[1m]) >= 0) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method)  / sum(rate(roundtrip_http_api_1_search_things_x_count{ditto_statusCode=~\"2[0-9]{2}\"}[1m]) > 0) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method))"
    },
    {
     "expr": "(sum(rate(roundtrip_http_other_sum{ditto_statusCode=~\"2[0-9]{2}\"}[1m]) >= 0) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method)  / sum(rate(roundtrip_http_other_count{ditto_statusCode=~\"2[0-9]{2}\"}[1m]) > 0) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method))"
    },
    {
     "expr": "(sum(rate(roundtrip_http_status_sum{ditto_statusCode=~\"2[0-9]{2}\"}[1m]) >= 0) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method)  / sum(rate(roundtrip_http_status_count{ditto_statusCode=~\"2[0-9]{2}\"}[1m]) > 0) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method))"
    },
    {
     "expr": "(sum(rate(roundtrip_http_status_health_sum{ditto_statusCode=~\"2[0-9]{2}\"}[1m]) >= 0) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method)  / sum(rate(roundtrip_http_status_health_count{ditto_statusCode=~\"2[0-9]{2}\"}[1m]) > 0) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method))"
    },
    {
     "expr": "(sum(rate(roundtrip_http_api_2_things_x_sum{ditto_statusCode=~\"2[0-9]{2}\"}[1m]) >= 0) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method)  / sum(rate(roundtrip_http_api_2_things_x_count{ditto_statusCode=~\"2[0-9]{2}\"}[1m]) > 0) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method))"
    },
    {
     "expr": "(sum(rate(roundtrip_http_api_2_search_things_x_sum{ditto_statusCode=~\"2[0-9]{2}\"}[1m]) >= 0) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method)  / sum(rate(roundtrip_http_api_2_search_things_x_count{ditto_statusCode=~\"2[0-9]{2}\"}[1m]) > 0) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method))"
    }
   ]
  },
  {
   "title": "# of Processed Http commands (20x)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(roundtrip_http_api_1_things_x_count{ditto_statusCode=~\"2[0-9]{2}\"}) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method)) - (sum(roundtrip_http_api_1_things_x_count{ditto_statusCode=~\"2[0-9]{2}\" } offset 1m) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method))"
    },
    {
     "expr": "(sum(roundtrip_http_api_1_search_things_x_count{ditto_statusCode=~\"2[0-9]{2}\"}) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method)) - (sum(roundtrip_http_api_1_search_things_x_count{ditto_statusCode=~\"2[0-9]{2}\" } offset 1m) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method))"
    },
    {
     "expr": "(sum(roundtrip_http_other_count{ditto_statusCode=~\"2[0-9]{2}\"}) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method)) - (sum(roundtrip_http_other_count{ditto_statusCode=~\"2[0-9]{2}\" } offset 1m) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method))"
    },
    {
     "expr": "(sum(roundtrip_http_status_count{ditto_statusCode=~\"2[0-9]{2}\"}) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method)) - (sum(roundtrip_http_status_count{ditto_statusCode=~\"2[0-9]{2}\" } offset 1m) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method))"
    },
    {
     "expr": "(sum(roundtrip_http_status_health_count{ditto_statusCode=~\"2[0-9]{2}\"}) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method)) - (sum(roundtrip_http_status_health_count{ditto_statusCode=~\"2[0-9]{2}\" } offset 1m) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method))"
    },
    {
     "expr": "(sum(roundtrip_http_api_2_things_x_count{ditto_statusCode=~\"2[0-9]{2}\"}) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method)) - (sum(roundtrip_http_api_2_things_x_count{ditto_statusCode=~\"2[0-9]{2}\" } offset 1m) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method))"
    },
    {
     "expr": "(sum(roundtrip_http_api_2_search_things_x_count{ditto_statusCode=~\"2[0-9]{2}\"}) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method)) - (sum(roundtrip_http_api_2_search_things_x_count{ditto_statusCode=~\"2[0-9]{2}\" } offset 1m) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method))"
    }
   ]
  },
  {
   "title": "Relative time per Trace",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(roundtrip_http_api_1_things_x_count{ditto_statusCode=~\"2[0-9]{2}\"}) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method)) - (sum(roundtrip_http_api_1_things_x_count{ditto_statusCode=~\"2[0-9]{2}\" } offset 1m) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method))"
    },
    {
     "expr": "(sum(roundtrip_http_api_1_search_things_x_count{ditto_statusCode=~\"2[0-9]{2}\"}) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method)) - (sum(roundtrip_http_api_1_search_things_x_count{ditto_statusCode=~\"2[0-9]{2}\" } offset 1m) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method))"
    },
    {
     "expr": "(sum(roundtrip_http_other_count{ditto_statusCode=~\"2[0-9]{2}\"}) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method)) - (sum(roundtrip_http_other_count{ditto_statusCode=~\"2[0-9]{2}\" } offset 1m) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method))"
    },
    {
     "expr": "(sum(roundtrip_http_status_count{ditto_statusCode=~\"2[0-9]{2}\"}) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method)) - (sum(roundtrip_http_status_count{ditto_statusCode=~\"2[0-9]{2}\" } offset 1m) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method))"
    },
    {
     "expr": "(sum(roundtrip_http_status_health_count{ditto_statusCode=~\"2[0-9]{2}\"}) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method)) - (sum(roundtrip_http_status_health_count{ditto_statusCode=~\"2[0-9]{2}\" } offset 1m) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method))"
    },
    {
     "expr": "(sum(roundtrip_http_api_2_things_x_count{ditto_statusCode=~\"2[0-9]{2}\"}) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method)) - (sum(roundtrip_http_api_2_things_x_count{ditto_statusCode=~\"2[0-9]{2}\" } offset 1m) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method))"
    },
    {
     "expr": "(sum(roundtrip_http_api_2_search_things_x_count{ditto_statusCode=~\"2[0-9]{2}\"}) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method)) - (sum(roundtrip_http_api_2_search_things_x_count{ditto_statusCode=~\"2[0-9]{2}\" } offset 1m) by (instance, ditto_entity_type, ditto_entity_subType, ditto_request_method))"
    }
   ]
  }
 ]
}