{
 "title": "[ditto] JVM Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Garbage Collection Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_seconds_sum[1m]) / rate(jvm_gc_seconds_count[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_seconds_count  - (jvm_gc_seconds_count offset 1m)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_count{segment=\"heap\"}) by (measure)",
     "legendFormat": "{{measure}}"
    }
   ]
  },
  {
   "title": "Non Heap Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_count{segment=\"non-heap\"}) by (measure)",
     "legendFormat": "{{measure}}"
    }
   ]
  },
  { "title": "JVM :: Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "sum(jvm_threads) by (measure)", "legendFormat": "{{measure}}" }
   ]
  },
  {
   "title": "Class Loading",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_class_loading) by (mode)",
     "legendFormat": "{{mode}}"
    }
   ]
  }
 ]
}