# Default values for eclipse-ditto.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  type: NodePort
  port: 8080
  loadBalancerIP:
    enabled: false
    address: 0.0.0.0

akka:
  actorSystemName: ditto-cluster
  remoting:
    port: 2551
  mgmthttp:
    port: 8558

global:
  timezone: Europe/Berlin

concierge:
  enabled: true
  name: concierge
  replicaCount: 1
  networkPolicy:
    enabled: true
  image:
    repository: docker.io/eclipse/ditto-concierge
    imagePullPolicy: IfNotPresent
    tag: 0.9.0
connectivity:
  enabled: true
  name: connectivity
  replicaCount: 1
  networkPolicy:
    enabled: true
  image:
    repository: docker.io/eclipse/ditto-connectivity
    imagePullPolicy: IfNotPresent
    tag: 0.9.0
things:
  enabled: true
  name: things
  replicaCount: 1
  networkPolicy:
    enabled: true
  image:
    repository: docker.io/eclipse/ditto-things
    imagePullPolicy: IfNotPresent
    tag: 0.9.0
search:
  enabled: true
  name: things-search
  replicaCount: 1
  networkPolicy:
    enabled: true
  image:
    repository: docker.io/eclipse/ditto-things-search
    imagePullPolicy: IfNotPresent
    tag: 0.9.0
policies:
  enabled: true
  name: policies
  replicaCount: 1
  networkPolicy:
    enabled: true
  image:
    repository: docker.io/eclipse/ditto-policies
    imagePullPolicy: IfNotPresent
    tag: 0.9.0
gateway:
  enabled: true
  name: gateway
  replicaCount: 1
  networkPolicy:
    enabled: true
  image:
    repository: docker.io/eclipse/ditto-gateway
    imagePullPolicy: IfNotPresent
    tag: 0.9.0

nginx:
  enabled: true
  replicaCount: 1
  name: nginx
  version: 1.15
  # Enable in case running on Openshift (needed for writing in pod)
  rootAccess: false
swagger:
  enabled: true
  name: swagger-ui
  replicaCount: 1
  version: 3.17.4
  networkPolicy:
    enabled: true
  # Enable in case running on Openshift (needed for writing in pod)
  rootAccess: false


##
## MongoDB chart configuration
##
mongodb:
## Disable in case an external MongoDB is used
  embedded:
    enabled: true
## https://github.com/helm/charts/blob/master/stable/mongodb/values.yaml
  usePassword: false
  image:
    tag: 3.6
  persistence:
    enabled: false
  apps:
    concierge:
      uri: mongodb://ditto-mongodb:27017/concierge
      ssl: false
    connectivity:
      uri: mongodb://ditto-mongodb:27017/connectivity
      ssl: false
    things:
      uri: mongodb://ditto-mongodb:27017/things
      ssl: false
    searchDB:
      uri: mongodb://ditto-mongodb:27017/searchDB
      ssl: false
    policies:
      uri: mongodb://ditto-mongodb:27017/policies
      ssl: false
