/*
 * Copyright (c) 2021 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 */
package org.eclipse.ditto.connectivity.service.messaging.tunnel;

import static org.eclipse.ditto.base.model.common.ConditionChecker.checkNotNull;

import java.net.SocketAddress;
import java.security.PublicKey;
import java.util.AbstractMap;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;

import org.apache.sshd.client.keyverifier.ServerKeyVerifier;
import org.apache.sshd.client.session.ClientSession;
import org.apache.sshd.common.config.keys.KeyUtils;

/**
 * Implementation of {@link org.apache.sshd.client.keyverifier.ServerKeyVerifier} that verifies the server key
 * against a given list of fingerprints in the format {@code <algorithm>:<fingerprint>}, where {@code algorithm} is the
 * digest algorithm use to calculate the fingerprint and the actual {@code fingerprint} as it is generated by the
 * ssh-keygen command line tool e.g. {@code sha256:MEULjymCqsBH6TkmQzKmA+G2qd+AJwarKwr84vUsQ+Y}.
 */
final class FingerprintVerifier implements ServerKeyVerifier {

    private final Set<String> knownHosts;

    /**
     * Instantiates a new {@code FingerprintVerifier}.
     *
     * @param knownHosts the list of known host fingerprints
     */
    FingerprintVerifier(final List<String> knownHosts) {
        this.knownHosts = Collections.unmodifiableSet(new HashSet<>(checkNotNull(knownHosts, "knownHosts")));
    }

    @Override
    public boolean verifyServerKey(final ClientSession clientSession,
            final SocketAddress remoteAddress,
            final PublicKey serverKey) {
        return knownHosts.stream()
                .map(knownHostFingerprint -> KeyUtils.checkFingerPrint(knownHostFingerprint, serverKey))
                .anyMatch(AbstractMap.SimpleImmutableEntry::getKey);
    }

    @Override
    public boolean equals(final Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        final FingerprintVerifier that = (FingerprintVerifier) o;
        return Objects.equals(knownHosts, that.knownHosts);
    }

    @Override
    public int hashCode() {
        return Objects.hash(knownHosts);
    }

    @Override
    public String toString() {
        return getClass().getSimpleName() + " [" +
                "knownHosts=" + knownHosts +
                "]";
    }
}
