ditto {
  dynamic-config-watcher {
    enabled = false
    enabled = ${?DITTO_DYNAMIC_CONFIG_ENABLED}
    file-path = "/opt/ditto/dynamic-config/dynamic.conf"
    file-path = ${?DITTO_DYNAMIC_CONFIG_FILE_PATH}
    poll-interval = 30s
    poll-interval = ${?DITTO_DYNAMIC_CONFIG_POLL_INTERVAL}
  }
}
