---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  clusterIP: None
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    app: mongodb
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
spec:
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: registry.access.redhat.com/rhscl/mongodb-36-rhel7
        resources:
          requests:
            cpu: "0.1"
            memory: "100Mi"
          limits:
            cpu: "0.5"
            memory: "250i"
        ports:
          - containerPort: 27017
        env:
        - name: TZ
          value: Europe/Berlin
        - name: MONGODB_USER
          value: "mongodb-user"
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGODB_PASSWORD        
        - name: MONGODB_DATABASE
          value: "iot-things"
        - name: MONGODB_ADMIN_PASSWORD        
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGODB_ADMIN_PASSWORD
