ditto {
  http {
    hostname = "localhost"
    port = 8095
  }

  metrics.prometheus.port = 9016

  timeseries {
    enforcement {
      required-permission = "READ_TS"
      required-permission = ${?TIMESERIES_REQUIRED_PERMISSION}
    }

    adapter {
      type = "mongodb"
      mongodb {
        uri = "mongodb://localhost:27017"
        uri = ${?TIMESERIES_MONGODB_URI}

        database = "ditto_ts"
        collection-prefix = "ts_"
        granularity = "seconds"
      }
    }
  }
}

pekko {
  management.http.port = 25640

  remote {
    watch-failure-detector {
      expected-response-after = 120s
    }

    artery {
      canonical.hostname = "127.0.0.1"
      canonical.port = 2563
      canonical.port = ${?REMOTE_PORT}
      bind.bind-timeout = 6s
      bind.bind-timeout = ${?ARTERY_BIND_TIMEOUT}
    }
  }

  cluster {
    failure-detector {
      expected-response-after = 120s
      threshold = 16.0
      acceptable-heartbeat-pause = 120s
    }

    seed-nodes = [
      "pekko://ditto-cluster@127.0.0.1:2552", # port of the policies service to join in cluster
      "pekko://ditto-cluster@"${pekko.remote.artery.canonical.hostname}":"${pekko.remote.artery.canonical.port}
    ]
  }
}
