apiVersion: v1
kind: Service
metadata:
  name: ditto-cluster 
spec:
  clusterIP: None
  ports:
  - port: 2551
    targetPort: 2551 
    protocol: TCP
  selector:
    app: policies
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: things
  labels:
    app: things
spec:
  template:
    metadata:
      labels:
        app: things
    spec:
      containers:
      - name: things
        image: docker.io/eclipse/ditto-things:latest
        command: ["/bin/sh"]
        args: ["-c", "sleep 10; java -jar /opt/ditto/starter.jar"]
        env:
        - name: BIND_HOSTNAME
          value: 0.0.0.0
        - name: INSTANCE_INDEX
          value: "1"
        - name: TZ
          value: Europe/Berlin
        - name: _JAVA_OPTIONS
          value: -Xms256m -Xmx256m -Xss512k -XX:MaxMetaspaceSize=128m -XX:+ExitOnOutOfMemoryError
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: things-search
  labels:
    app: things-search
spec:
  template:
    metadata:
      labels:
        app: things-search
    spec:
      containers:
      - name: things-search
        image: docker.io/eclipse/ditto-things-search:latest
        command: ["/bin/sh"]
        args: ["-c", "sleep 10; java -jar /opt/ditto/starter.jar"]
        env:
        - name: BIND_HOSTNAME
          value: 0.0.0.0
        - name: INSTANCE_INDEX
          value: "1"
        - name: TZ
          value: Europe/Berlin
        - name: _JAVA_OPTIONS
          value: -Xms256m -Xmx256m -Xss512k -XX:MaxMetaspaceSize=128m -XX:+ExitOnOutOfMemoryError
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: policies
  labels:
    app: policies
spec:
  template:
    metadata:
      labels:
        app: policies
    spec:
      containers:
      - name: policies
        image: docker.io/eclipse/ditto-policies:latest
        env:
        - name: BIND_HOSTNAME
          value: 0.0.0.0
        - name: INSTANCE_INDEX
          value: "1"
        - name: TZ
          value: Europe/Berlin
        - name: _JAVA_OPTIONS
          value: -Xms256m -Xmx256m -Xss512k -XX:MaxMetaspaceSize=128m -XX:+ExitOnOutOfMemoryError -Dditto.cluster.become-leader=true
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: docker.io/eclipse/ditto-gateway:latest
        command: ["/bin/sh"]
        args: ["-c", "sleep 10; java -jar /opt/ditto/starter.jar"]
        env:
        - name: BIND_HOSTNAME
          value: 0.0.0.0
        - name: ENABLE_DUMMY_AUTH
          value: "true"
        - name: INSTANCE_INDEX
          value: "1"
        - name: TZ
          value: Europe/Berlin
        - name: _JAVA_OPTIONS
          value: -Xms256m -Xmx256m -Xss512k -XX:MaxMetaspaceSize=128m -XX:+ExitOnOutOfMemoryError
