{{- if .Values.nginx.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eclipse-ditto.fullname" . }}-nginx
  labels:
    app.kubernetes.io/name: {{ include "eclipse-ditto.name" . }}-nginx
{{ include "eclipse-ditto.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  strategy:
  {{- with .Values.nginx.updateStrategy }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "eclipse-ditto.name" . }}-nginx
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "eclipse-ditto.name" . }}-nginx
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- with .Values.nginx.additionalLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/nginx-conf: {{ include (print $.Template.BasePath "/nginx-configmap.yaml") . | sha256sum }}
        checksum/nginx-config: {{ include (print $.Template.BasePath "/nginx-config.yaml") . | sha256sum }}
        {{- with .Values.nginx.additionalAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
    {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}-nginx
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.nginx.image.imagePullPolicy }}
          env:
          {{- if .Values.nginx.extraEnv }}
            {{- toYaml .Values.nginx.extraEnv | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- if .Values.nginx.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.nginx.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.nginx.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.nginx.livenessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-htpasswd
              mountPath: /etc/nginx/nginx.htpasswd
              subPath: nginx.htpasswd
            - name: nginx-cors
              mountPath: /etc/nginx/nginx-cors.conf
              subPath: nginx-cors.conf
            - name: nginx-index
              mountPath: /etc/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: nginx-conf
          configMap:
            name: {{ .Release.Name }}-nginx-conf
        - name: nginx-htpasswd
          configMap:
            name: {{ .Release.Name }}-nginx-config-nginx-htpasswd
        - name: nginx-cors
          configMap:
            name: {{ .Release.Name }}-nginx-config-nginx-cors-conf
        - name: nginx-index
          configMap:
            name: {{ .Release.Name }}-nginx-config-index-html
{{- if .Values.nginx.rootAccess }}
      securityContext:
        runAsUser: 0
{{- end }}
      {{- with .Values.nginx.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.nginx.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.nginx.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
